Conexion03/config/routes.rb
Rails.application.routes.draw do
  resources :proys
  resources :alumnos
  resources :proys
  resources :alumnos
  resources :proys
  resources :alumnos

end

Conexion03/app/models/alumno.rb
class Alumno < ActiveRecord::Base
end

Conexion03/app/models/proy.rb
class Proy < ActiveRecord::Base
  belongs_to :Alumno
end

Conexion03/app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  before_action :set_alumno, only: [:show, :edit, :update, :destroy]

  # GET /alumnos
  # GET /alumnos.json
  def index
    @alumnos = Alumno.all
  end

  # GET /alumnos/1
  # GET /alumnos/1.json
  def show
  end

  # GET /alumnos/new
  def new
    @alumno = Alumno.new
  end

  # GET /alumnos/1/edit
  def edit
  end

  # POST /alumnos
  # POST /alumnos.json
  def create
    @alumno = Alumno.new(alumno_params)

    respond_to do |format|
      if @alumno.save
        format.html { redirect_to @alumno, notice: 'Alumno was successfully created.' }
        format.json { render :show, status: :created, location: @alumno }
      else
        format.html { render :new }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnos/1
  # PATCH/PUT /alumnos/1.json
  def update
    respond_to do |format|
      if @alumno.update(alumno_params)
        format.html { redirect_to @alumno, notice: 'Alumno was successfully updated.' }
        format.json { render :show, status: :ok, location: @alumno }
      else
        format.html { render :edit }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1
  # DELETE /alumnos/1.json
  def destroy
    @alumno.destroy
    respond_to do |format|
      format.html { redirect_to alumnos_url, notice: 'Alumno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno
      @alumno = Alumno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumno_params
      params.require(:alumno).permit(:nombre, :apellido, :nac)
    end
end

Conexion03/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Conexion03/app/controllers/proys_controller.rb
class ProysController < ApplicationController
  before_action :set_proy, only: [:show, :edit, :update, :destroy]

  # GET /proys
  # GET /proys.json
  def index
    @proys = Proy.all
  end

  # GET /proys/1
  # GET /proys/1.json
  def show
  end

  # GET /proys/new
  def new
    @proy = Proy.new
  end

  # GET /proys/1/edit
  def edit
  end

  # POST /proys
  # POST /proys.json
  def create
    @proy = Proy.new(proy_params)

    respond_to do |format|
      if @proy.save
        format.html { redirect_to @proy, notice: 'Proy was successfully created.' }
        format.json { render :show, status: :created, location: @proy }
      else
        format.html { render :new }
        format.json { render json: @proy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proys/1
  # PATCH/PUT /proys/1.json
  def update
    respond_to do |format|
      if @proy.update(proy_params)
        format.html { redirect_to @proy, notice: 'Proy was successfully updated.' }
        format.json { render :show, status: :ok, location: @proy }
      else
        format.html { render :edit }
        format.json { render json: @proy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proys/1
  # DELETE /proys/1.json
  def destroy
    @proy.destroy
    respond_to do |format|
      format.html { redirect_to proys_url, notice: 'Proy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proy
      @proy = Proy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proy_params
      params.require(:proy).permit(:nombre_proy, :horas, :Alumno_id)
    end
end

Conexion03/app/helpers/alumnos_helper.rb
module AlumnosHelper
end

Conexion03/app/helpers/application_helper.rb
module ApplicationHelper
end

Conexion03/app/helpers/proys_helper.rb
module ProysHelper
end

Conexion03/app/views/alumnos/_form.html.erb
<%= form_for(@alumno) do |f| %>
  <% if @alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alumno.errors.count, "error") %> prohibited this alumno from being saved:</h2>

      <ul>
      <% @alumno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :nac %><br>
    <%= f.date_select :nac %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Conexion03/app/views/alumnos/edit.html.erb
<h1>Editing Alumno</h1>

<%= render 'form' %>

<%= link_to 'Show', @alumno %> |
<%= link_to 'Back', alumnos_path %>

Conexion03/app/views/alumnos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alumnos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Nac</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alumnos.each do |alumno| %>
      <tr>
        <td><%= alumno.nombre %></td>
        <td><%= alumno.apellido %></td>
        <td><%= alumno.nac %></td>
        <td><%= link_to 'Show', alumno %></td>
        <td><%= link_to 'Edit', edit_alumno_path(alumno) %></td>
        <td><%= link_to 'Destroy', alumno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alumno', new_alumno_path %>

Conexion03/app/views/alumnos/new.html.erb
<h1>New Alumno</h1>

<%= render 'form' %>

<%= link_to 'Back', alumnos_path %>

Conexion03/app/views/alumnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @alumno.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @alumno.apellido %>
</p>

<p>
  <strong>Nac:</strong>
  <%= @alumno.nac %>
</p>

<%= link_to 'Edit', edit_alumno_path(@alumno) %> |
<%= link_to 'Back', alumnos_path %>

Conexion03/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Conexion03</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Conexion03/app/views/proys/_form.html.erb
<%= form_for(@proy) do |f| %>
  <% if @proy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proy.errors.count, "error") %> prohibited this proy from being saved:</h2>

      <ul>
      <% @proy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_proy %><br>
    <%= f.text_field :nombre_proy %>
  </div>
  <div class="field">
    <%= f.label :horas %><br>
    <%= f.number_field :horas %>
  </div>
  <div class="field">
    <%= f.label :Alumno_id %><br>
    <%= f.text_field :Alumno_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Conexion03/app/views/proys/edit.html.erb
<h1>Editing Proy</h1>

<%= render 'form' %>

<%= link_to 'Show', @proy %> |
<%= link_to 'Back', proys_path %>

Conexion03/app/views/proys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Proys</h1>

<table>
  <thead>
    <tr>
      <th>Nombre proy</th>
      <th>Horas</th>
      <th>Alumno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proys.each do |proy| %>
      <tr>
        <td><%= proy.nombre_proy %></td>
        <td><%= proy.horas %></td>
        <td><%= proy.Alumno %></td>
        <td><%= link_to 'Show', proy %></td>
        <td><%= link_to 'Edit', edit_proy_path(proy) %></td>
        <td><%= link_to 'Destroy', proy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proy', new_proy_path %>

Conexion03/app/views/proys/new.html.erb
<h1>New Proy</h1>

<%= render 'form' %>

<%= link_to 'Back', proys_path %>

Conexion03/app/views/proys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre proy:</strong>
  <%= @proy.nombre_proy %>
</p>

<p>
  <strong>Horas:</strong>
  <%= @proy.horas %>
</p>

<p>
  <strong>Alumno:</strong>
  <%= @proy.Alumno %>
</p>

<%= link_to 'Edit', edit_proy_path(@proy) %> |
<%= link_to 'Back', proys_path %>